export default [
  {
    index: 1,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A1 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 2,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A2 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 3,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A3 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 4,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A4 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 5,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A5 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 6,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A6 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 7,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A7 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 8,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A8 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 9,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A9 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
  {
    index: 10,
    image: 'http://www.sclance.com/pngs/image-placeholder-png/image_placeholder_png_698131.png',
    title: 'A10 title',
    userName: 'User Name',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla molestie tempor. Phasellus faucibus posuere rhoncus. Nam eu nisi nisi. Proin pretium porta odio, et cursus enim.',
    datePublished: new Date(),
    upVotes: 20,
  },
];
